"use client";

import { useEffect, useState } from 'react';
import api from '../lib/api';
import { Search, Trash2, Check, X, Loader2, Download, AlertCircle, User as UserIcon } from 'lucide-react';
import jsPDF from 'jspdf';

interface ScanRecord {
  id: number;
  user_name: string;
  filename: string;
  prediction: string;
  confidence: string;
  heatmap_url: string;
  created_at: string;
}

export default function HistoryPage() {
  const [history, setHistory] = useState<ScanRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);
  const [confirmDelete, setConfirmDelete] = useState<number | null>(null);
  const [isExporting, setIsExporting] = useState<number | null>(null);
  const [toast, setToast] = useState<{ msg: string; type: 'error' | 'success' } | null>(null);

  const fetchHistory = async () => {
    try {
      const response = await api.get('/history');
      setHistory(response.data);
    } catch (e) {
      triggerToast("Failed to fetch history from server.", "error");
    } finally {
      setLoading(false);
    }
  };

  const triggerToast = (msg: string, type: 'error' | 'success') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 4000);
  };

  const exportToPDF = async (scan: ScanRecord) => {
    setIsExporting(scan.id);
    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("NEUROSCAN AI REPORT", 20, 20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Clinical Diagnostic Classification", 20, 28);

      doc.setTextColor(51, 65, 85);
      doc.setFontSize(10);
      doc.text(`Radiologist/Researcher: ${scan.user_name}`, 20, 50);
      doc.text(`Patient File: ${scan.filename}`, 20, 56);
      doc.text(`Record ID: ${scan.id}`, 20, 62);
      doc.text(`Timestamp: ${new Date(scan.created_at).toLocaleString()}`, 20, 68);
      doc.line(20, 72, 190, 72);

      doc.setFillColor(241, 245, 249);
      doc.roundedRect(20, 80, 170, 40, 4, 4, 'F');
      doc.setFont("helvetica", "bold");
      doc.text("AI FINDING:", 30, 92);

      const isHealthy = scan.prediction === 'notumor';
      doc.setTextColor(isHealthy ? 5 : 220, isHealthy ? 150 : 38, isHealthy ? 105 : 38);
      doc.setFontSize(24);
      doc.text(scan.prediction.toUpperCase(), 30, 108);
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139);
      doc.text(`Confidence Score: ${scan.confidence}`, 130, 108);

      const imgUrl = scan.heatmap_url;
      const imgData = await new Promise<string>((resolve, reject) => {
        const img = new Image();
        img.setAttribute('crossOrigin', 'anonymous');
        img.onload = () => {
          const canvas = document.createElement("canvas");
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext("2d");
          if (!ctx) return reject("Canvas Error");
          ctx.drawImage(img, 0, 0);
          resolve(canvas.toDataURL("image/jpeg", 0.9));
        };
        img.onerror = () => reject("Image Load Failed");
        img.src = imgUrl;
      });

      doc.setTextColor(15, 23, 42);
      doc.setFont("helvetica", "bold");
      doc.text("Analysis Visualization (Grad-CAM):", 20, 135);
      doc.addImage(imgData, 'JPEG', 20, 140, 100, 100);

      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      const disclaimer = "NOTICE: This analysis was generated by a Deep Learning model. This report is for decision-support purposes and must be validated by a clinical radiologist.";
      doc.text(doc.splitTextToSize(disclaimer, 170), 20, 275);

      doc.save(`NeuroScan_${scan.user_name}_${scan.id}.pdf`);
      triggerToast("Report generated successfully", "success");
    } catch (err) {
      console.error(err);
      triggerToast("Could not generate PDF. Check backend server.", "error");
    } finally {
      setIsExporting(null);
    }
  };

  const deleteRecord = async (id: number) => {
    try {
      await api.delete(`/history/${id}`);
      setHistory(prev => prev.filter(item => item.id !== id));
      setConfirmDelete(null);
      triggerToast("Record deleted successfully", "success");
    } catch (e) {
      triggerToast("Deletion failed", "error");
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const filteredHistory = history.filter(scan => {
    const filename = scan.filename?.toLowerCase() || "";
    const prediction = scan.prediction?.toLowerCase() || "";
    const userName = scan.user_name?.toLowerCase() || "";
    const term = searchTerm.toLowerCase();
    return filename.includes(term) || prediction.includes(term) || userName.includes(term);
  });

  return (
    <div className="p-4 md:p-10 space-y-6 md:space-y-8 max-w-[1400px] mx-auto min-h-screen bg-gradient-to-br from-white via-blue-50/40 to-white">
      {/* Toast Notification - responsive positioning */}
      {toast && (
        <div
          className={`fixed top-4 right-4 md:top-8 md:right-8 z-[100] flex items-center gap-3 px-4 md:px-6 py-3 md:py-4 rounded-2xl shadow-xl border backdrop-blur-lg text-sm md:text-base ${
            toast.type === 'success'
              ? 'bg-white border-blue-200 text-blue-700'
              : 'bg-white border-red-200 text-red-600'
          }`}
        >
          {toast.type === 'success' ? <Check size={18} /> : <AlertCircle size={18} />}
          <span className="font-semibold">{toast.msg}</span>
        </div>
      )}

      {/* Header - stacks on mobile */}
      <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-6 md:p-8 rounded-2xl md:rounded-3xl border border-blue-100 shadow-xl shadow-blue-100/40">
        <div>
          <h1 className="text-2xl md:text-4xl font-bold text-blue-900 tracking-tight">Clinical Records</h1>
          <p className="text-sm md:text-base text-blue-500 font-medium mt-1">Relational diagnostic classification archive</p>
        </div>
        <div className="bg-blue-50 px-4 md:px-6 py-3 md:py-4 rounded-xl md:rounded-2xl border border-blue-100">
          <p className="text-[10px] md:text-xs font-bold text-blue-400 uppercase tracking-widest text-center">Total Entries</p>
          <p className="text-xl md:text-2xl font-bold text-blue-900 text-center">{history.length}</p>
        </div>
      </header>

      {/* Search Bar - full width, adjusts padding */}
      <div className="relative group w-full">
        <Search
          className="absolute left-4 md:left-5 top-1/2 -translate-y-1/2 text-blue-300 group-focus-within:text-blue-600 transition-all"
          size={18}
        />
        <input
          type="text"
          placeholder="Search by Radiologist, Filename, or Result..."
          className="w-full pl-10 md:pl-14 pr-4 md:pr-6 py-4 md:py-5 bg-white border border-blue-100 rounded-2xl md:rounded-3xl shadow-lg shadow-blue-100/30 focus:outline-none focus:ring-4 focus:ring-blue-200 focus:border-blue-400 transition-all duration-300 font-semibold text-blue-900 text-sm md:text-base"
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Table container with horizontal scroll on mobile */}
      <div className="bg-white rounded-2xl md:rounded-3xl shadow-2xl shadow-blue-100/40 border border-blue-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left min-w-[800px] md:min-w-full">
            <thead className="bg-blue-50/60 border-b border-blue-100">
              <tr>
                <th className="px-4 md:px-10 py-4 md:py-6 text-[10px] md:text-xs font-bold text-blue-400 uppercase tracking-widest">
                  Researcher / Patient File
                </th>
                <th className="px-4 md:px-10 py-4 md:py-6 text-[10px] md:text-xs font-bold text-blue-400 uppercase tracking-widest">
                  Categorization
                </th>
                <th className="px-4 md:px-10 py-4 md:py-6 text-right text-[10px] md:text-xs font-bold text-blue-400 uppercase tracking-widest">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-blue-50">
              {filteredHistory.map((scan) => (
                <tr key={scan.id} className="group transition-all duration-300 hover:bg-blue-50/50">
                  <td className="px-4 md:px-10 py-4 md:py-8">
                    <div className="flex items-center gap-3 md:gap-5">
                      <div className="p-2 md:p-4 bg-blue-50 rounded-xl md:rounded-2xl text-blue-400 group-hover:text-blue-600 transition-all">
                        <UserIcon size={16} className="md:w-5 md:h-5" />
                      </div>
                      <div className="min-w-0">
                        <p className="font-bold text-blue-900 text-sm md:text-lg truncate">{scan.user_name}</p>
                        <p className="text-[10px] md:text-xs text-blue-400 font-medium mt-1 uppercase tracking-tighter truncate">
                          File: {scan.filename} | ID: {scan.id}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 md:px-10 py-4 md:py-8">
                    <span
                      className={`inline-flex items-center px-3 md:px-4 py-1 md:py-2 rounded-xl md:rounded-2xl text-[10px] md:text-xs font-bold uppercase border shadow-sm whitespace-nowrap ${
                        scan.prediction === 'notumor'
                          ? 'bg-blue-50 text-blue-700 border-blue-200'
                          : 'bg-red-50 text-red-600 border-red-200'
                      }`}
                    >
                      {scan.prediction} ({scan.confidence})
                    </span>
                  </td>
                  <td className="px-4 md:px-10 py-4 md:py-8 text-right">
                    <div className="flex justify-end items-center gap-2 md:gap-4">
                      <button
                        onClick={() => exportToPDF(scan)}
                        disabled={isExporting === scan.id}
                        className="flex items-center gap-1 md:gap-2 px-3 md:px-6 py-2 md:py-3 bg-blue-600 text-white rounded-xl md:rounded-2xl text-[10px] md:text-xs font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-200 whitespace-nowrap"
                      >
                        {isExporting === scan.id ? (
                          <Loader2 size={12} className="md:w-4 md:h-4 animate-spin" />
                        ) : (
                          <Download size={12} className="md:w-4 md:h-4" />
                        )}
                        <span className="hidden sm:inline">REPORT</span>
                        <span className="sm:hidden">PDF</span>
                      </button>
                      {confirmDelete === scan.id ? (
                        <div className="flex gap-1 md:gap-2">
                          <button
                            onClick={() => deleteRecord(scan.id)}
                            className="bg-red-500 text-white p-1.5 md:p-3 rounded-xl md:rounded-2xl"
                          >
                            <Check size={14} className="md:w-4 md:h-4" />
                          </button>
                          <button
                            onClick={() => setConfirmDelete(null)}
                            className="bg-blue-100 text-blue-600 p-1.5 md:p-3 rounded-xl md:rounded-2xl"
                          >
                            <X size={14} className="md:w-4 md:h-4" />
                          </button>
                        </div>
                      ) : (
                        <button
                          onClick={() => setConfirmDelete(scan.id)}
                          className="p-1.5 md:p-3 text-blue-200 hover:text-red-500 transition-all opacity-0 group-hover:opacity-100"
                        >
                          <Trash2 size={16} className="md:w-5 md:h-5" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {loading && (
          <div className="p-10 md:p-20 text-center font-semibold text-blue-300 animate-pulse uppercase tracking-widest text-xs md:text-sm">
            Synchronizing Clinical History...
          </div>
        )}
        {!loading && filteredHistory.length === 0 && (
          <div className="p-10 md:p-20 text-center font-semibold text-slate-400 uppercase tracking-widest text-xs md:text-sm">
            No matching records found.
          </div>
        )}
      </div>
    </div>
  );
}