"use client";

import { useEffect, useState } from 'react';
import api from '../lib/api';
import { Search, Trash2, Calendar, Check, X, Loader2, Download, AlertCircle } from 'lucide-react';
import jsPDF from 'jspdf';

// 1. TypeScript Interface to fix 'never' type errors
interface ScanRecord {
  id: number;
  filename: string;
  prediction: string;
  confidence: number;
  heatmap_url: string;
  created_at: string;
}

export default function HistoryPage() {
  const [history, setHistory] = useState<ScanRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);
  const [confirmDelete, setConfirmDelete] = useState<number | null>(null);
  const [isExporting, setIsExporting] = useState<number | null>(null);
  const [toast, setToast] = useState<{msg: string, type: 'error' | 'success'} | null>(null);

  const fetchHistory = async () => {
    try {
      const response = await api.get('/history');
      setHistory(response.data);
    } catch (e) {
      triggerToast("Failed to fetch history from server.", "error");
    } finally {
      setLoading(false);
    }
  };

  const triggerToast = (msg: string, type: 'error' | 'success') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 4000);
  };

  // --- FIXED PDF LOGIC ---
  const exportToPDF = async (scan: ScanRecord) => {
    setIsExporting(scan.id);
    
    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      
      // 1. Header Design
      doc.setFillColor(15, 23, 42); 
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("NEUROSCAN AI REPORT", 20, 20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Clinical Diagnostic Classification", 20, 28);

      // 2. Report Metadata
      doc.setTextColor(51, 65, 85);
      doc.text(`Patient File: ${scan.filename}`, 20, 55);
      doc.text(`Record ID: ${scan.id}`, 20, 61);
      doc.text(`Timestamp: ${new Date(scan.created_at).toLocaleString()}`, 20, 67);
      doc.line(20, 72, 190, 72);

      // 3. Prediction Section (Fixing the Color Overload)
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(20, 80, 170, 40, 4, 4, 'F');
      doc.setFont("helvetica", "bold");
      doc.text("AI FINDING:", 30, 92);
      
      const isHealthy = scan.prediction === 'notumor';
      // FIX: Passing numbers individually instead of an array
      if (isHealthy) {
        doc.setTextColor(5, 150, 105); // Green
      } else {
        doc.setTextColor(220, 38, 38); // Red
      }

      doc.setFontSize(24);
      doc.text(scan.prediction.toUpperCase(), 30, 108);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139);
      doc.text(`Confidence Score: ${(scan.confidence * 100).toFixed(2)}%`, 130, 108);

      // 4. Image Processing
      const baseUrl = "http://127.0.0.1:8000/";
      const imgUrl = scan.heatmap_url.startsWith('http') 
        ? scan.heatmap_url 
        : `${baseUrl}${scan.heatmap_url}`;

      const imgData = await new Promise<string>((resolve, reject) => {
        const img = new Image();
        img.setAttribute('crossOrigin', 'anonymous');
        img.onload = () => {
          const canvas = document.createElement("canvas");
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext("2d");
          if (!ctx) return reject("Canvas Error");
          ctx.drawImage(img, 0, 0);
          resolve(canvas.toDataURL("image/jpeg", 0.9));
        };
        img.onerror = () => reject("Image Load Failed");
        img.src = imgUrl;
      });

      doc.setTextColor(15, 23, 42);
      doc.setFont("helvetica", "bold");
      doc.text("Analysis Visualization (Grad-CAM):", 20, 135);
      doc.addImage(imgData, 'JPEG', 20, 140, 100, 100);

      // 5. Disclaimer
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      const disclaimer = "NOTICE: This analysis was generated by a Deep Learning model. This report is for decision-support purposes and must be validated by a clinical radiologist.";
      doc.text(doc.splitTextToSize(disclaimer, 170), 20, 275);

      doc.save(`NeuroScan_${scan.id}.pdf`);
      triggerToast("Report generated successfully", "success");
    } catch (err) {
      console.error(err);
      triggerToast("Could not embed MRI image. Check backend.", "error");
    } finally {
      setIsExporting(null);
    }
  };

  const deleteRecord = async (id: number) => {
    try {
      await api.delete(`/history/${id}`);
      setHistory(prev => prev.filter(item => item.id !== id));
      setConfirmDelete(null);
      triggerToast("Record deleted successfully", "success");
    } catch (e) {
      triggerToast("Deletion failed", "error");
    }
  };

  useEffect(() => { fetchHistory(); }, []);

  const filteredHistory = history.filter(scan => 
    scan.filename.toLowerCase().includes(searchTerm.toLowerCase()) ||
    scan.prediction.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-10 space-y-8 max-w-[1400px] mx-auto min-h-screen relative">
      {/* Custom Toast */}
      {toast && (
        <div className={`fixed top-8 right-8 z-[100] flex items-center gap-3 px-6 py-4 rounded-2xl shadow-xl border animate-in slide-in-from-top-4 ${
          toast.type === 'success' ? 'bg-slate-900 text-white' : 'bg-rose-600 text-white'
        }`}>
          {toast.type === 'success' ? <Check size={18} /> : <AlertCircle size={18} />}
          <span className="font-bold text-sm tracking-tight">{toast.msg}</span>
        </div>
      )}

      <header className="flex justify-between items-center bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm">
        <div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tighter uppercase italic">Clinical Records</h1>
          <p className="text-slate-500 font-medium">Historical diagnostic classification archive</p>
        </div>
        <div className="bg-slate-50 px-6 py-3 rounded-2xl border border-slate-100">
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1 text-center">Total Entries</p>
          <p className="text-2xl font-black text-slate-900 text-center">{history.length}</p>
        </div>
      </header>

      <div className="relative group max-w-xl">
        <Search className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-300 group-focus-within:text-blue-500" size={20} />
        <input 
          type="text" 
          placeholder="Filter by filename or result..." 
          className="w-full pl-14 pr-6 py-5 bg-white border border-slate-200 rounded-3xl shadow-sm focus:outline-none focus:ring-4 focus:ring-blue-500/10 transition-all font-semibold"
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-200 overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-slate-50/50 border-b border-slate-100">
            <tr>
              <th className="px-10 py-6 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Patient Data</th>
              <th className="px-10 py-6 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Categorization</th>
              <th className="px-10 py-6 text-right text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {filteredHistory.map((scan) => (
              <tr key={scan.id} className="hover:bg-blue-50/20 transition-all group">
                <td className="px-10 py-8">
                  <div className="flex items-center gap-5">
                    <div className="p-4 bg-slate-50 rounded-2xl text-slate-400 group-hover:text-blue-500 transition-all">
                      <Calendar size={20} />
                    </div>
                    <div>
                      <p className="font-black text-slate-800 text-lg leading-tight tracking-tight">{scan.filename}</p>
                      <p className="text-[11px] text-slate-400 font-mono mt-1 uppercase">ID: {scan.id}</p>
                    </div>
                  </div>
                </td>
                <td className="px-10 py-8">
                  <span className={`inline-flex items-center gap-2 px-4 py-2 rounded-2xl text-[11px] font-black uppercase border tracking-tighter
                    ${scan.prediction === 'notumor' ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-rose-50 text-rose-600 border-rose-100'}`}>
                    {scan.prediction}
                  </span>
                </td>
                <td className="px-10 py-8 text-right">
                  <div className="flex justify-end items-center gap-4">
                    <button 
                      onClick={() => exportToPDF(scan)}
                      disabled={isExporting === scan.id}
                      className="flex items-center gap-2 px-6 py-3 bg-slate-900 text-white rounded-2xl text-[11px] font-black hover:bg-blue-600 transition-all disabled:opacity-50"
                    >
                      {isExporting === scan.id ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
                      REPORT
                    </button>
                    
                    {confirmDelete === scan.id ? (
                      <div className="flex gap-2 animate-in fade-in zoom-in duration-200">
                        <button onClick={() => deleteRecord(scan.id)} className="bg-rose-600 text-white p-3 rounded-2xl shadow-lg shadow-rose-200"><Check size={18}/></button>
                        <button onClick={() => setConfirmDelete(null)} className="bg-slate-200 text-slate-600 p-3 rounded-2xl"><X size={18}/></button>
                      </div>
                    ) : (
                      <button onClick={() => setConfirmDelete(scan.id)} className="p-3 text-slate-200 hover:text-rose-500 transition-all opacity-0 group-hover:opacity-100">
                        <Trash2 size={20} />
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {loading && <div className="p-20 text-center font-bold text-slate-300 animate-pulse uppercase tracking-widest text-xs tracking-widest">Synchronizing Neural History...</div>}
      </div>
    </div>
  );
}